// <auto-generated />
using System;
using MemberEligibility.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemberEligibility.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923013723_FixSeedPlanNames")]
    partial class FixSeedPlanNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemberEligibility.Api.Models.Claim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_number");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_status");

                    b.Property<DateOnly?>("DatePaid")
                        .HasColumnType("date")
                        .HasColumnName("date_paid");

                    b.Property<DateOnly>("DateReceived")
                        .HasColumnType("date")
                        .HasColumnName("date_received");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payee_name");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<DateOnly>("StatementDate")
                        .HasColumnType("date")
                        .HasColumnName("statement_date");

                    b.HasKey("Id")
                        .HasName("pk_claims");

                    b.ToTable("claims", (string)null);
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.ClaimLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AllowedCharges")
                        .HasColumnType("numeric")
                        .HasColumnName("allowed_charges");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint")
                        .HasColumnName("claim_id");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_status");

                    b.Property<decimal>("Coinsurance")
                        .HasColumnType("numeric")
                        .HasColumnName("coinsurance");

                    b.Property<decimal>("Copay")
                        .HasColumnType("numeric")
                        .HasColumnName("copay");

                    b.Property<DateOnly>("DateOfService")
                        .HasColumnType("date")
                        .HasColumnName("date_of_service");

                    b.Property<decimal>("Deductible")
                        .HasColumnType("numeric")
                        .HasColumnName("deductible");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal>("PaidByInsurer")
                        .HasColumnType("numeric")
                        .HasColumnName("paid_by_insurer");

                    b.Property<decimal>("ProviderCharges")
                        .HasColumnType("numeric")
                        .HasColumnName("provider_charges");

                    b.Property<string>("RemarkCode")
                        .HasColumnType("text")
                        .HasColumnName("remark_code");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_description");

                    b.Property<decimal>("WhatYouOwe")
                        .HasColumnType("numeric")
                        .HasColumnName("what_you_owe");

                    b.HasKey("Id")
                        .HasName("pk_claim_lines");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_claim_lines_claim_id");

                    b.ToTable("claim_lines", (string)null);
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<string>("PcpName")
                        .HasColumnType("text")
                        .HasColumnName("pcp_name");

                    b.Property<string>("PcpPhone")
                        .HasColumnType("text")
                        .HasColumnName("pcp_phone");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubscriberNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscriber_number");

                    b.Property<DateOnly?>("TermDate")
                        .HasColumnType("date")
                        .HasColumnName("term_date");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_enrollments_member_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_enrollments_plan_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.IdCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_status");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<string>("RxBin")
                        .HasColumnType("text")
                        .HasColumnName("rx_bin");

                    b.Property<string>("RxGrp")
                        .HasColumnType("text")
                        .HasColumnName("rx_grp");

                    b.Property<string>("RxId")
                        .HasColumnType("text")
                        .HasColumnName("rx_id");

                    b.Property<string>("RxPcn")
                        .HasColumnType("text")
                        .HasColumnName("rx_pcn");

                    b.HasKey("Id")
                        .HasName("pk_id_cards");

                    b.ToTable("id_cards", (string)null);
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.Plan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BehavioralHealthPhone")
                        .HasColumnType("text")
                        .HasColumnName("behavioral_health_phone");

                    b.Property<string>("ClaimInquiryPhone")
                        .HasColumnType("text")
                        .HasColumnName("claim_inquiry_phone");

                    b.Property<string>("ClaimsAddress")
                        .HasColumnType("text")
                        .HasColumnName("claims_address");

                    b.Property<string>("CmsContractNumber")
                        .HasColumnType("text")
                        .HasColumnName("cms_contract_number");

                    b.Property<decimal>("CopayEr")
                        .HasColumnType("numeric")
                        .HasColumnName("copay_er");

                    b.Property<decimal>("CopayPcp")
                        .HasColumnType("numeric")
                        .HasColumnName("copay_pcp");

                    b.Property<decimal>("CopaySpecialist")
                        .HasColumnType("numeric")
                        .HasColumnName("copay_specialist");

                    b.Property<string>("CustomerServicePhone")
                        .HasColumnType("text")
                        .HasColumnName("customer_service_phone");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_number");

                    b.Property<string>("MemberServicesPhone")
                        .HasColumnType("text")
                        .HasColumnName("member_services_phone");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payer_id");

                    b.Property<string>("PharmacyHelpDeskPhone")
                        .HasColumnType("text")
                        .HasColumnName("pharmacy_help_desk_phone");

                    b.Property<string>("PlanBenefitPackageNumber")
                        .HasColumnType("text")
                        .HasColumnName("plan_benefit_package_number");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_name");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_type");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.ClaimLine", b =>
                {
                    b.HasOne("MemberEligibility.Api.Models.Claim", null)
                        .WithMany("Lines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_lines_claims_claim_id");
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.Enrollment", b =>
                {
                    b.HasOne("MemberEligibility.Api.Models.Member", "Member")
                        .WithMany("Enrollments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_members_member_id");

                    b.HasOne("MemberEligibility.Api.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_plans_plan_id");

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.Claim", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MemberEligibility.Api.Models.Member", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
